### ISSUE TITLE
Not able to clone this in android studio

### ISSUE THREAD

**Issue by satishsojitra** [ipragmatech/Android-Magento-Rest-Api-Integration#1]
Hi

I am not able to clone in android studio. I am not getting any files while cloning through android studio. If I download zip from here then it will throwing error for @drawable and can not resolved symbol R.

Please help me out to clone this in android studio and run in emulator.

Thanks

**Comment by ipragmatechadmin** [comment]
Looks like you have issue compiling the app, can you clean the project and build again?

**Comment by satishsojitra** [comment]
Hi

Thanks for replying after 10Months :)

On Tue, Jun 28, 2016 at 3:38 PM, iPragmatech Admin <notifications@github.com
> wrote:

> Looks like you have issue compiling the app, can you clean the project and
> build again?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipragmatech/Android-Magento-Rest-Api-Integration/issues/1#issuecomment-229007811>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMcux1Sqj_wx_XibJTBKPKJ24gkY--zlks5qQPK0gaJpZM4Fj9iY>
> .
>



-- 





Business Card link :  https://mybizcard.co/sojitra.satishb.558678
Join KvGroup <http://kvgroup4all.blogspot.com/>
*♫~♫♫ ╒r!≡√\/ds ╒☻rΣ\/εr ♫~♫♫ *

**Comment by ipragmatechadmin** [comment]
I noticed this message today only..somehow missed this for a long time :)...were you able to launch the app ?

**Comment by satishsojitra** [comment]
No I was not able to launch app after rebuilding and cleaning. then I
dropped it :)

On Tue, Jun 28, 2016 at 3:46 PM, iPragmatech Admin <notifications@github.com
> wrote:

> I noticed this message today only..somehow missed this for a long time
> :)...were you able to launch the app ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipragmatech/Android-Magento-Rest-Api-Integration/issues/1#issuecomment-229009396>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMcux1wi6YC3_FAnGYHk_SjbLBecFKq7ks5qQPR5gaJpZM4Fj9iY>
> .
>



-- 





Business Card link :  https://mybizcard.co/sojitra.satishb.558678
Join KvGroup <http://kvgroup4all.blogspot.com/>
*♫~♫♫ ╒r!≡√\/ds ╒☻rΣ\/εr ♫~♫♫ *

**Comment by satishsojitra** [comment]
I got some other solution.

On Tue, Jun 28, 2016 at 3:53 PM, satish sojitra <satish.sojitra@gmail.com>
wrote:

> No I was not able to launch app after rebuilding and cleaning. then I
> dropped it :)
>
> On Tue, Jun 28, 2016 at 3:46 PM, iPragmatech Admin <
> notifications@github.com> wrote:
>
>> I noticed this message today only..somehow missed this for a long time
>> :)...were you able to launch the app ?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ipragmatech/Android-Magento-Rest-Api-Integration/issues/1#issuecomment-229009396>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AMcux1wi6YC3_FAnGYHk_SjbLBecFKq7ks5qQPR5gaJpZM4Fj9iY>
>> .
>>
>
>
>
> --
>
>
>
>
>
> Business Card link :  https://mybizcard.co/sojitra.satishb.558678
> Join KvGroup <http://kvgroup4all.blogspot.com/>
> *♫~♫♫ ╒r!≡√\/ds ╒☻rΣ\/εr ♫~♫♫ *
>
>


-- 





Business Card link :  https://mybizcard.co/sojitra.satishb.558678
Join KvGroup <http://kvgroup4all.blogspot.com/>
*♫~♫♫ ╒r!≡√\/ds ╒☻rΣ\/εr ♫~♫♫ *
